### ISSUE TITLE
Abbr File missing 

### ISSUE THREAD

**Issue by Khyati-Microcrispr** [BIOIN-401-Project-8/NLMChemTaggerNormalizer#1]
hi 
Thanks for the github. I am gettting an error. please help if possible.

/NLMChemTaggerNormalizer$ ./run_Chemical_PubTator.sh sample_ctg_output_fornlmtagger abbr output
Mon Dec 23 09:27:01 UTC 2024
INPUT=/home/kp36143d/NLMChemTaggerNormalizer/sample_ctg_output_fornlmtagger
ABBR=/home/kp36143d/NLMChemTaggerNormalizer/abbr
OUTPUT=/home/kp36143d/NLMChemTaggerNormalizer/output
is dir
Loading configuration
Loading abbreviation frequency file
Traceback (most recent call last):
  File "/home/kp36143d/NLMChemTaggerNormalizer/CHEM_NORM/src/normalize.py", line 48, in <module>
    abbr_freq_dict = json.load(abbr_freq_file)
  File "/home/kp36143d/miniconda3/envs/NLMtagger/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/kp36143d/miniconda3/envs/NLMtagger/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/kp36143d/miniconda3/envs/NLMtagger/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/kp36143d/miniconda3/envs/NLMtagger/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon Dec 23 09:27:01 UTC 2024
Done.

**Comment by zy2376** [comment]
Hi, it seems that some files in the data directory (e.g., CHEM_NORM/data/abbr_frequency_2020.json.gz) are tracked by Git LFS, but the actual file is missing and cannot be downloaded. Could you please share the real file or upload it properly to the repository? 
Look forward for your response. Thank you !
